#!/usr/bin/env bash
# This script will display "Holberton School" 10 times,
# but the 9th iteration, displays Holberton School
# and then Hi on a new line.
i=1

while [ $i -lt "10" ]
do
    echo "Holberton School"

    if [ $i -eq "9" ]
    then
        echo "Hi"
        echo "Holberton School"
    fi

    ((i += 1))
done
