#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
#
#   - Display hours from 0 to 12
#   - Display minutes from 1 to 59
hour=0
minutes=1
while [ $hours -ne 13 ]
do
    echo "Hour: $hours"
    ((hours++))
    while [ $minutes -ne 60 ]
    do
	echo $minutes
	((minutes++))
    done
    ((minutes = 1))
done
