#!/usr/bin/env bash
# Displays:
#
#   The content of the current directory
#   In a list format
#   Where only the part of the name after the first dash is displayed (refer to the example)
curr_content=$("ls")
list=$(ls)
for i in $list
do
    echo "$i" | cut -d'-' -f 2
done
